%YAML:1.0

#common parameters
imu_topic: "/imu0"
image_topic: "/cam0/image_raw"
output_path: "Initialize_result.csv"         # vins outputs will be wrttento vins_folder_path + output_path

#camera calibration 
#model_type: PINHOLE
model_type:  KANNALA_BRANDT
camera_name: camera
image_width: 752
image_height: 480
#distortion_parameters:
#   k1: -2.917e-01
#   k2: 8.228e-02
#   p1: 5.333e-05
#  p2: -1.578e-04
#projection_parameters:
#   fx: 4.616e+02
#   fy: 4.603e+02
#  cx: 3.630e+02
#  cy: 2.481e+02
#projection_parameters:
#   k2: -0.011529628921724093
#   k3:  0.003756747872753678
#   K4: -0.0016847865380580638
#   K5:  0.001653238186183769
#   mu: 441.3901888738877
#   mv: 441.0899648995731
#   u0: 399.6195821784267
#   v0: 229.4781273451998
projection_parameters:
   k2: -0.024623350887912173
   k3: -0.0004661578976785472
   K4: -0.0020942152744516406
   K5: -0.00007306889657714406
   mu: 367.44806889546425
   mv: 367.0562580834955
   u0: 388.43030393075725
   v0: 244.82403612263656

    

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning. 
ex_calib_result_path: "ex_calib_result.yaml"  # If you choose 1 or 2, the extrinsic calibration result will be written vins_folder_path + ex_calib_result_path.                        
#If you choose 0 or 1, you should write down the following matrix.
#Rotation from camera frame to imu frame, imu^R_cam
extrinsicRotation: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
#   data: [0, -1, 0, 
#           1, 0, 0, 
#           0, 0, 1]
#   data:  [0.05591635439655884,0.9981297129512015,0.02470703209514279,
#           0.998350836773727,0.05621666225790301,0.01163157761352537,
#           0.01299877010324552,0.02401589075035217,0.9996270649433568]
   data: [-0.0005701, -0.99999681, -0.00246227, 
           0.99999271, -0.0005608, -0.00377782, 
           0.00377643, -0.00246441, 0.99998983]
#Translation from camera frame to imu frame, imu^T_cam
extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
#   data: [-1.5216915745012177e-01,4.1399345703738361e-04,-1.4364120265680422e-01]
#   data: [-0.02,-0.06, 0.01]
#   data: [0.0025199,-0.04312059, 0.02232081]
   data: [0.006365331136653198,0.0472792618187829,0.02019903864926934]
#    data: [-0.02,-0.06, 0.01]
#feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 30            # min distance between two features 
freq: 10                # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points

#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

#imu parameters       The more accurate parameters you provide, the better performance
acc_n: 0.2          # accelerometer measurement noise standard deviation. #0.2
gyr_n: 0.02         # gyroscope measurement noise standard deviation.     #0.05
acc_w: 0.0002         # accelerometer bias random work noise standard deviation.  #0.02
gyr_w: 2.0e-5       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.81007     # gravity magnitude
#acc_n: 7.6509e-02
#gyr_n: 9.0086e-03
#acc_w: 5.3271e-02
#gyr_w: 5.5379e-05
#g_norm: 9.8189
#loop closure parameters
loop_closure: 1   #if you want to use loop closure to minimize the drift, set loop_closure true and give your brief pattern file path and vocabulary file path accordingly;
                     #also give the camera calibration file same as feature_tracker node
pattern_file: "brief_pattern.yml"
voc_file: "brief_k10L6.bin"
min_loop_num: 25


